version: '3.9'

volumes:
  user-db:
    driver: local

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  user-db:
    image: postgres:latest
    container_name: user-database
    ports:
      - 5431:5431
    environment:
      - POSTGRES_USER=user_app
      - POSTGRES_DB=user_app
      - POSTGRES_PASSWORD=user_app
    restart: always
    command: -p 5431
    networks:
      - kong-net
    volumes:
      - user-db:/var/lib/postgresql/data

  user-service:
    image: user-service:latest
    container_name: user-service
    depends_on:
      - user-db
    ports:
      - 8003:8003
    environment:
      - SPRING_APPLICATION_NAME=user_app
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5431/user_app
      - SPRING_DATASOURCE_USERNAME=user_app
      - SPRING_DATASOURCE_PASSWORD=user_app
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    networks:
      - kong-net