apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: joaotdev/mtsds-where2go:eureka-server-service
          resources:
#            requests:
#              cpu: 100m
#              memory: 64Mi
#            limits:
#              cpu: 200m
#              memory: 128Mi
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_APPLICATION_NAME
              value: "eureka-server-service"
            - name: EUREKA_CLIENT_REGISTER-WITH-EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH-REGISTRY
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  selector:
    app: eureka-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761