version: '3.9'

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  user-login-service:
    image: paulocunhaestg/user-login:latest
    container_name: user-login-service
    ports:
      - 8004:8004
    environment:
      - SPRING_APPLICATION_NAME=user_app
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5431/user_app
      - SPRING_DATASOURCE_USERNAME=user_app
      - SPRING_DATASOURCE_PASSWORD=user_app
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    networks:
      - kong-net